quiet: false
with-expecter: true
disable-version-string: true
dir: '{{trimPrefix .PackagePath "github.com/reshifr/secure-env/"}}/mock'
mockname: '{{trimPrefix .InterfaceName "I"}}'
filename: '{{lower (trimPrefix .InterfaceName "I")}}.go'
outpkg: "mock"
packages:
  github.com/reshifr/secure-env/core/crypt:
