quiet: false
with-expecter: true
disable-version-string: true
dir: '{{trimPrefix .PackagePath "github.com/reshifr/secure-env/"}}/mock'
mockname: '{{.InterfaceName}}'
filename: '{{lower (.InterfaceName)}}.go'
outpkg: '{{.PackageName}}_mock'
packages:
  github.com/reshifr/secure-env/core/crypto:
    interfaces:
      CipherIV:
