quiet: false
with-expecter: true
disable-version-string: true
dir: 'mocks/{{trimPrefix .PackagePath "github.com/reshifr/secure-env/"}}'
mockname: '{{trimPrefix .InterfaceName "I"}}'
filename: '{{lower (trimPrefix .InterfaceName "I")}}.go'
outpkg: "{{.PackageName}}_mock"
packages:
  github.com/reshifr/secure-env/core:
  github.com/reshifr/secure-env/core/crypt:
