name: Integration Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Run integration test
        run: |
          make integration-test
