name: Miscellaneous

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: reshifr/secure-env
