name: Unit Test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Running unit test
        run: |
          make test
